# -*- coding: utf-8 -*-
"""lista_tupla.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B2WuIM08uLu5CZY4uy7oUXhpWDant8Pj

1 - Use um dicionário para armazenar informações sobre uma pessoa que você conheça. Armazene seu primeiro nome, o sobrenome, a idade e a cidade em que ela vive. Você deverá ter chaves como primeiro_nome, sobrenome, idade, e cidade. Por fim, mostre cada informação armazenada em seu dicionário.
"""

import pandas as pd
dados={"primeiro_nome":["jardel", "jardiely", "jorge", "edna"], "sobrenome":["praxedes","praxedes","praxedes", "lourenço"], "idade":[21, 19,42,39], "cidade": ["lucena","lucena", "lucena", "lucena"]}
dados_df=pd.DataFrame(dados)
display(dados_df)